### PR TITLE
Changes so that tao works with BOINC 7.23.0 

### PR DESCRIPTION
**Pull request by Kevnroux**
- added build directory in .gitignore
- changed .gitmodules to https 
- changed all CMakeLists.txt to include file type to get rid of warnings for add_library and add_excecutable 
- added #include for filesys.h in tao_work_generator for read_file_malloc in filesys.cpp definition previously defined in util.cpp 
- change to CMakeLists.txt in boinc folder to include script_validator.cpp for in add_executable(tao_validator ....) to fix undefined reference to init_result and cleanup_result error  
- Commenting out duplicate definitions of  validate_handler_usage and validate_handler_init in tao_validation_policy.cxx since defined in script_validator.cpp

### CODE REVIEW

**Comment by Kevnroux** [comment]
- added build directory in .gitignore
- changed .gitmodules to https
- changed all CMakeLists.txt to include file type to get rid of warnings for add_library and add_excecutable
- added #include for filesys.h in tao_work_generator for read_file_malloc in filesys.cpp definition previously defined in util.cpp
- change to CMakeLists.txt in boinc folder to include script_validator.cpp for in add_executable(tao_validator ....) to fix undefined reference to init_result and cleanup_result error
- Commenting out duplicate definitions of validate_handler_usage and validate_handler_init in tao_validation_policy.cxx since defined in script_validator.cpp
